# Metro Manila Flood Level Predictor

## Importing libraries and dataset

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('AEGISDataset.csv')
data.head()

lat         lon  flood_heig  elevation  precipitat
0  14.640394  121.055708           0  54.553295           9
1  14.698299  121.002132           0  21.856272          10
2  14.698858  121.100261           0  69.322807          16
3  14.571310  120.983334           0  10.987241           8
4  14.762232  121.075735           0  87.889847          18

## Dropping possibly misleading zeroes

In [ ]:
#only run once
indic = []
for name in data:
    print(name)
    if name != 'flood_heig':
        for number in range(len(data[name])):
            if data[name][number] == 0:
                if number not in indic:
                    indic.append(number)

In [ ]:
data = data.drop(index=indic, axis = 0)
print(data.head(70))

## Normalizing the data

In [11]:
x = data.drop('flood_heig', axis=1)
y = data['flood_heig']

In [12]:
from sklearn.preprocessing import normalize
y1 = y/y.max()
print(y1)

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
3505    1.0
3506    1.0
3507    1.0
3508    1.0
3509    1.0
Name: flood_heig, Length: 3510, dtype: float64


In [13]:
from sklearn.preprocessing import minmax_scale
x1 = minmax_scale(x)
print(x1)

[[0.65839316 0.64031012 0.59404389 0.42857143]
 [0.77698544 0.41819665 0.23799818 0.47619048]
 [0.77813041 0.8250149  0.75487265 0.76190476]
 ...
 [0.50022767 0.91138561 0.06286233 0.61904762]
 [0.47165457 0.52549714 0.24329394 0.33333333]
 [0.69242955 0.63498201 0.58220847 0.42857143]]


## Preparing dataset for training and testing

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x1,y1,train_size=0.7)